export const Constants = {
  WhiteSpace: /\s/,
  NumberStart: /[-+0-9]/,
  NumberChar: /[-+0-9.p]/,
  NameChar: /[0-9.A-Za-z_]/,
  OpeningBrace: '{',
  ClosingBrace: '}',
  Semicolon: ';',
  SectionStart: '[',
  SectionEnd: ']',
  StringDelimiter: '"',
  Domain: 'bereich',
  Header: 'Kopf',
  RawSections: ['DB_GEO', 'PROZESS_PARAMETER'],
  EndOfFile: 'end_of_file',
};
